[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "alloc", "compiler_builtins"]

[build]
#build-stage = 1
target = "x86_64-unknown-none"
#target = "stable-x86_64-unknown-none"

#[target.x86_64-unknown-none]
#linker = "rust-lld"
#rustflags = [ "-C", "link-arg=-fuse-ld=lld" ]
#linker = "cc"
#rustflags = [ "-C", "linker-flavor=gcc"]
